{"timestamp": "2025-01-18T21:00:17.072558", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-18T21:00:17.078978", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-18T21:00:17.091102", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-18T21:00:17.111737", "level": "WARNING", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "verify_token", "line": 557, "message": "Token verification failed: Invalid token: session expired"}
{"timestamp": "2025-01-18T21:00:17.113554", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "revoke_token", "line": 610, "message": "Error revoking token: 401: Invalid token: session expired"}
{"timestamp": "2025-01-18T21:00:17.126066", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth", "function": "dispatch", "line": 108, "message": "Auth middleware error: 1 validation errors:\n  {'type': 'string_type', 'loc': ('response', 'message'), 'msg': 'Input should be a valid string', 'input': {'success': False, 'error_code': 'GENERAL_ERROR', 'message': 'logout_successful', 'status_code': 500}}\n", "exception": {"type": "ResponseValidationError", "message": "1 validation errors:\n  {'type': 'string_type', 'loc': ('response', 'message'), 'msg': 'Input should be a valid string', 'input': {'success': False, 'error_code': 'GENERAL_ERROR', 'message': 'logout_successful', 'status_code': 500}}\n", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/venv/lib/python3.12/site-packages/anyio/streams/memory.py\", line 111, in receive\n    return self.receive_nowait()\n           ^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/root/projects/school-attendance-management-software/venv/lib/python3.12/site-packages/anyio/streams/memory.py\", line 106, in receive_nowait\n    raise WouldBlock\n", "anyio.WouldBlock\n", "\nDuring handling of the above exception, another exception occurred:\n\n", "Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/venv/lib/python3.12/site-packages/anyio/streams/memory.py\", line 124, in receive\n    return receiver.item\n           ^^^^^^^^^^^^^\n", "AttributeError: 'MemoryObjectItemReceiver' object has no attribute 'item'\n", "\nDuring handling of the above exception, another exception occurred:\n\n", "Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/venv/lib/python3.12/site-packages/starlette/middleware/base.py\", line 157, in call_next\n    message = await recv_stream.receive()\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/root/projects/school-attendance-management-software/venv/lib/python3.12/site-packages/anyio/streams/memory.py\", line 126, in receive\n    raise EndOfStream\n", "anyio.EndOfStream\n", "\nDuring handling of the above exception, another exception occurred:\n\n", "Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/middleware/auth.py\", line 78, in dispatch\n    response = await call_next(request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/root/projects/school-attendance-management-software/venv/lib/python3.12/site-packages/starlette/middleware/base.py\", line 163, in call_next\n    raise app_exc\n", "  File \"/root/projects/school-attendance-management-software/venv/lib/python3.12/site-packages/starlette/middleware/base.py\", line 149, in coro\n    await self.app(scope, receive_or_disconnect, send_no_error)\n", "  File \"/root/projects/school-attendance-management-software/venv/lib/python3.12/site-packages/starlette/middleware/base.py\", line 185, in __call__\n    with collapse_excgroups():\n", "  File \"/usr/lib/python3.12/contextlib.py\", line 158, in __exit__\n    self.gen.throw(value)\n", "  File \"/root/projects/school-attendance-management-software/venv/lib/python3.12/site-packages/starlette/_utils.py\", line 83, in collapse_excgroups\n    raise exc\n", "  File \"/root/projects/school-attendance-management-software/venv/lib/python3.12/site-packages/starlette/middleware/base.py\", line 187, in __call__\n    response = await self.dispatch_func(request, call_next)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/root/projects/school-attendance-management-software/app/middleware/request_id.py\", line 11, in dispatch\n    response = await call_next(request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/root/projects/school-attendance-management-software/venv/lib/python3.12/site-packages/starlette/middleware/base.py\", line 163, in call_next\n    raise app_exc\n", "  File \"/root/projects/school-attendance-management-software/venv/lib/python3.12/site-packages/starlette/middleware/base.py\", line 149, in coro\n    await self.app(scope, receive_or_disconnect, send_no_error)\n", "  File \"/root/projects/school-attendance-management-software/venv/lib/python3.12/site-packages/starlette/middleware/cors.py\", line 93, in __call__\n    await self.simple_response(scope, receive, send, request_headers=headers)\n", "  File \"/root/projects/school-attendance-management-software/venv/lib/python3.12/site-packages/starlette/middleware/cors.py\", line 144, in simple_response\n    await self.app(scope, receive, send)\n", "  File \"/root/projects/school-attendance-management-software/venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py\", line 62, in __call__\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n", "  File \"/root/projects/school-attendance-management-software/venv/lib/python3.12/site-packages/starlette/_exception_handler.py\", line 62, in wrapped_app\n    raise exc\n", "  File \"/root/projects/school-attendance-management-software/venv/lib/python3.12/site-packages/starlette/_exception_handler.py\", line 51, in wrapped_app\n    await app(scope, receive, sender)\n", "  File \"/root/projects/school-attendance-management-software/venv/lib/python3.12/site-packages/starlette/routing.py\", line 715, in __call__\n    await self.middleware_stack(scope, receive, send)\n", "  File \"/root/projects/school-attendance-management-software/venv/lib/python3.12/site-packages/starlette/routing.py\", line 735, in app\n    await route.handle(scope, receive, send)\n", "  File \"/root/projects/school-attendance-management-software/venv/lib/python3.12/site-packages/starlette/routing.py\", line 288, in handle\n    await self.app(scope, receive, send)\n", "  File \"/root/projects/school-attendance-management-software/venv/lib/python3.12/site-packages/starlette/routing.py\", line 76, in app\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n", "  File \"/root/projects/school-attendance-management-software/venv/lib/python3.12/site-packages/starlette/_exception_handler.py\", line 62, in wrapped_app\n    raise exc\n", "  File \"/root/projects/school-attendance-management-software/venv/lib/python3.12/site-packages/starlette/_exception_handler.py\", line 51, in wrapped_app\n    await app(scope, receive, sender)\n", "  File \"/root/projects/school-attendance-management-software/venv/lib/python3.12/site-packages/starlette/routing.py\", line 73, in app\n    response = await f(request)\n               ^^^^^^^^^^^^^^^^\n", "  File \"/root/projects/school-attendance-management-software/venv/lib/python3.12/site-packages/fastapi/routing.py\", line 327, in app\n    content = await serialize_response(\n              ^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/root/projects/school-attendance-management-software/venv/lib/python3.12/site-packages/fastapi/routing.py\", line 176, in serialize_response\n    raise ResponseValidationError(\n", "fastapi.exceptions.ResponseValidationError: 1 validation errors:\n  {'type': 'string_type', 'loc': ('response', 'message'), 'msg': 'Input should be a valid string', 'input': {'success': False, 'error_code': 'GENERAL_ERROR', 'message': 'logout_successful', 'status_code': 500}}\n\n"]}}
{"timestamp": "2025-01-18T21:00:31.753253", "level": "INFO", "logger": "SchoolAttendanceLogger", "module": "auth", "function": "login", "line": 216, "message": "Login attempt initiated", "request_id": "303734f8-1522-410b-857a-8260871a1c8a"}
{"timestamp": "2025-01-18T21:00:32.043117", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "authenticate_user", "line": 710, "message": "Generating tokens", "user_id": "24"}
{"timestamp": "2025-01-18T21:00:32.048275", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "create_token", "line": 448, "message": "Token created successfully", "user_id": "24"}
{"timestamp": "2025-01-18T21:00:32.048913", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "create_token", "line": 448, "message": "Token created successfully", "user_id": "24"}
{"timestamp": "2025-01-18T21:00:32.049198", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "authenticate_user", "line": 727, "message": "Token expiration times"}
{"timestamp": "2025-01-18T21:00:32.049606", "level": "INFO", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "authenticate_user", "line": 767, "message": "User logged in successfully", "user_id": "24"}
{"timestamp": "2025-01-18T21:00:32.050071", "level": "INFO", "logger": "SchoolAttendanceLogger", "module": "auth", "function": "login", "line": 236, "message": "Login successful", "request_id": "303734f8-1522-410b-857a-8260871a1c8a", "user_id": "24"}
{"timestamp": "2025-01-18T21:00:32.130575", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "create_token", "line": 448, "message": "Token created successfully", "user_id": "24"}
{"timestamp": "2025-01-18T21:00:32.131068", "level": "INFO", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "refresh_access_token", "line": 894, "message": "Access token refreshed successfully", "user_id": "24"}
{"timestamp": "2025-01-18T21:00:32.131717", "level": "INFO", "logger": "SchoolAttendanceLogger", "module": "auth", "function": "refresh_token", "line": 358, "message": "Token refresh successful"}
{"timestamp": "2025-01-18T21:01:32.609447", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-18T21:01:32.621083", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-18T21:01:32.637943", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-18T21:01:32.640325", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-18T21:01:32.654581", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-18T21:02:33.812397", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-18T21:02:34.256979", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-18T21:02:35.954644", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-18T21:02:36.057243", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-18T21:02:39.073016", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-18T21:03:32.640713", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-18T21:03:32.677641", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-18T21:03:32.721450", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-18T21:03:32.727402", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-18T21:03:32.797290", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-18T21:04:32.584319", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-18T21:04:32.587445", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-18T21:04:32.602127", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-18T21:04:32.606702", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-18T21:04:32.617278", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-18T21:05:32.461894", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-18T21:05:32.465355", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-18T21:05:32.486617", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-18T21:05:32.489412", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-18T21:05:32.515410", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-18T21:06:32.460149", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-18T21:06:32.461276", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-18T21:06:32.472374", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-18T21:06:32.474293", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-18T21:06:32.483196", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-18T21:06:32.582234", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "create_token", "line": 448, "message": "Token created successfully", "user_id": "24"}
{"timestamp": "2025-01-18T21:06:32.583975", "level": "INFO", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "refresh_access_token", "line": 894, "message": "Access token refreshed successfully", "user_id": "24"}
{"timestamp": "2025-01-18T21:06:32.587245", "level": "INFO", "logger": "SchoolAttendanceLogger", "module": "auth", "function": "refresh_token", "line": 358, "message": "Token refresh successful"}
{"timestamp": "2025-01-18T21:06:34.271416", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "create_token", "line": 448, "message": "Token created successfully", "user_id": "24"}
{"timestamp": "2025-01-18T21:06:34.272678", "level": "INFO", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "refresh_access_token", "line": 894, "message": "Access token refreshed successfully", "user_id": "24"}
{"timestamp": "2025-01-18T21:06:34.273441", "level": "INFO", "logger": "SchoolAttendanceLogger", "module": "auth", "function": "refresh_token", "line": 358, "message": "Token refresh successful"}
{"timestamp": "2025-01-18T21:07:35.584111", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-18T21:07:35.586323", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-18T21:07:35.597756", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-18T21:07:35.602078", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-18T21:07:35.613004", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-18T21:08:34.658787", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-18T21:08:34.700078", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-18T21:08:34.730553", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-18T21:08:34.733216", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-18T21:08:34.793679", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-18T21:09:20.235795", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "create_token", "line": 448, "message": "Token created successfully", "user_id": "24"}
{"timestamp": "2025-01-18T21:09:20.236544", "level": "INFO", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "refresh_access_token", "line": 894, "message": "Access token refreshed successfully", "user_id": "24"}
{"timestamp": "2025-01-18T21:09:20.237283", "level": "INFO", "logger": "SchoolAttendanceLogger", "module": "auth", "function": "refresh_token", "line": 358, "message": "Token refresh successful"}
{"timestamp": "2025-01-18T21:10:20.848627", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-18T21:10:20.866467", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-18T21:10:20.895014", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-18T21:10:20.897812", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-18T21:10:20.926736", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-18T21:11:20.834822", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-18T21:11:20.835842", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-18T21:11:20.846761", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-18T21:11:20.849096", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-18T21:11:20.859249", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-18T21:12:20.513110", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-18T21:12:20.515661", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-18T21:12:20.534848", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-18T21:12:20.537125", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-18T21:12:20.549567", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-18T21:13:21.577724", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-18T21:13:21.580067", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-18T21:13:21.605422", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-18T21:13:21.607226", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-18T21:13:21.620927", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-18T21:14:21.269859", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-18T21:14:21.271137", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-18T21:14:21.289563", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-18T21:14:21.291767", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-18T21:14:21.304565", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-18T21:15:21.586963", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-18T21:15:21.590396", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-18T21:15:21.619963", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-18T21:15:21.625849", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-18T21:15:21.640927", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-18T21:16:20.828421", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-18T21:16:20.830558", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-18T21:16:20.846920", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-18T21:16:20.850262", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-18T21:16:20.863138", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-18T21:17:21.597847", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-18T21:17:21.599232", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-18T21:17:21.615845", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-18T21:17:21.618302", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-18T21:17:21.629320", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-18T21:18:22.585606", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-18T21:18:22.587337", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-18T21:18:22.630106", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-18T21:18:22.641367", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-18T21:18:22.660781", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-18T21:19:23.586659", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-18T21:19:23.587860", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-18T21:19:23.601480", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-18T21:19:23.604811", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-18T21:19:23.620411", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-18T21:20:24.594870", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-18T21:20:24.596250", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-18T21:20:24.614310", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-18T21:20:24.616657", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-18T21:20:24.630120", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-18T21:21:25.590046", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-18T21:21:25.592825", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-18T21:21:25.605853", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-18T21:21:25.611618", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-18T21:21:25.622214", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-18T21:22:26.612829", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-18T21:22:26.655826", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-18T21:22:26.705329", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-18T21:22:26.712402", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-18T21:22:26.848775", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-18T21:23:27.628361", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-18T21:23:27.714626", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-18T21:23:27.904565", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-18T21:23:28.037365", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-18T21:23:34.938246", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-18T21:24:53.951768", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-18T21:24:58.639738", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-18T21:25:09.764129", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-18T21:25:18.073998", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-18T21:26:25.375217", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-18T21:28:08.280315", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-18T21:28:30.754461", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-18T21:28:47.984654", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-18T21:28:48.175377", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-18T21:28:48.539252", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-18T21:28:48.553746", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-18T21:28:48.649556", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-18T21:28:48.868961", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-18T21:28:51.217699", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-18T21:29:09.293807", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-18T21:29:45.688427", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-18T21:30:26.228515", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-19T04:23:23.198696", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "create_token", "line": 448, "message": "Token created successfully", "user_id": "24"}
{"timestamp": "2025-01-19T04:23:23.203409", "level": "INFO", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "refresh_access_token", "line": 894, "message": "Access token refreshed successfully", "user_id": "24"}
{"timestamp": "2025-01-19T04:23:23.204709", "level": "INFO", "logger": "SchoolAttendanceLogger", "module": "auth", "function": "refresh_token", "line": 358, "message": "Token refresh successful"}
{"timestamp": "2025-01-19T04:24:24.330541", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:24:24.346404", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-19T04:24:24.366997", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:24:24.371667", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:24:24.439829", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:25:23.787394", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:25:23.790158", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-19T04:25:23.822682", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:25:23.830395", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:25:23.846969", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:26:23.908853", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:26:23.916148", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-19T04:26:23.943997", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:26:23.949727", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:26:23.973467", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:27:23.887169", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:27:23.889432", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-19T04:27:23.915098", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:27:23.921055", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:27:23.938493", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:28:24.009960", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:28:24.011890", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-19T04:28:24.041203", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:28:24.046044", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:28:24.068153", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:29:24.850949", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:29:24.853454", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-19T04:29:24.884389", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:29:24.887812", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:29:24.907342", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:30:25.777489", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:30:25.780850", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-19T04:30:25.805753", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:30:25.811212", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:30:25.831633", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:31:27.107812", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:31:27.118804", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-19T04:31:27.151272", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:31:27.160528", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:31:27.332141", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:32:28.032490", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:32:28.037526", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-19T04:32:28.062166", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:32:28.066592", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:32:28.083405", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:33:28.689008", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:33:28.693381", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-19T04:33:28.731423", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:33:28.740975", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:33:28.765780", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:34:30.300539", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:34:30.303405", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-19T04:34:30.328184", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:34:30.333965", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:34:30.353462", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:35:30.736694", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:35:30.739680", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-19T04:35:30.760746", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:35:30.764454", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:35:30.782485", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:36:31.802963", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:36:31.806685", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-19T04:36:31.835346", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:36:31.838974", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:36:31.855561", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:37:32.895986", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:37:32.897480", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-19T04:37:32.919273", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:37:32.922811", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:37:32.941176", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:38:33.889323", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:38:33.891251", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-19T04:38:33.912824", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:38:33.916574", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:38:33.934177", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:39:35.314454", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:39:35.316647", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-19T04:39:35.339531", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:39:35.345369", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:39:35.365098", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:40:35.798131", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:40:35.800215", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-19T04:40:35.821447", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:40:35.824731", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:40:35.841847", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:41:36.946337", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:41:36.949552", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-19T04:41:36.984114", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:41:36.988349", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:41:37.010064", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:42:38.261099", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:42:38.262975", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-19T04:42:38.283281", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:42:38.287949", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:42:38.306516", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:43:38.935266", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:43:38.937445", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-19T04:43:38.968641", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:43:38.980307", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:43:39.006522", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:52:28.125543", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:52:28.149308", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-19T04:52:28.180098", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:52:28.181971", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-19T04:52:28.200694", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:52:28.202874", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-19T04:52:28.231268", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:52:28.234442", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-19T04:52:28.259513", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:52:28.261617", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-19T04:52:28.341046", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:52:28.345645", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:52:28.352193", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:52:28.356225", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:52:28.478788", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:52:28.512657", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:52:28.515838", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:52:28.525779", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:52:28.533231", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:52:28.564883", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:52:29.605296", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "create_token", "line": 448, "message": "Token created successfully", "user_id": "24"}
{"timestamp": "2025-01-19T04:52:29.608082", "level": "INFO", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "refresh_access_token", "line": 894, "message": "Access token refreshed successfully", "user_id": "24"}
{"timestamp": "2025-01-19T04:52:29.609296", "level": "INFO", "logger": "SchoolAttendanceLogger", "module": "auth", "function": "refresh_token", "line": 358, "message": "Token refresh successful"}
{"timestamp": "2025-01-19T04:52:29.680192", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:52:29.721421", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:52:29.736143", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:52:29.770878", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:52:29.791806", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:52:30.165437", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:52:30.171676", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-19T04:52:30.246553", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:52:30.249938", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-19T04:52:30.315993", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:52:30.322742", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-19T04:52:30.394128", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:52:30.400234", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:52:30.406333", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:52:30.419335", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:52:30.426466", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:52:30.431827", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:52:30.480495", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:52:30.483145", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:52:30.485850", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:53:30.935019", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:53:30.944742", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-19T04:53:31.000926", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:53:31.017520", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:53:31.053296", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:54:30.975510", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:54:30.979719", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-19T04:54:31.005295", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:54:31.011168", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:54:31.032746", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:55:31.284803", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:55:31.287232", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-19T04:55:31.309176", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:55:31.312667", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:55:31.332756", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:56:31.014386", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:56:31.019298", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-19T04:56:31.058479", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:56:31.065368", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:56:31.086399", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:57:30.807924", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:57:30.810694", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-19T04:57:30.835386", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:57:30.842957", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:57:30.867992", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:58:31.831361", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:58:31.838294", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-19T04:58:31.879917", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:58:31.887428", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:58:31.912090", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:59:32.890736", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:59:32.894847", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-19T04:59:32.930738", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T04:59:32.938265", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T04:59:32.967589", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T05:00:33.928549", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T05:00:33.935137", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-19T05:00:33.963771", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T05:00:33.968636", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T05:00:33.987745", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T05:01:35.136173", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T05:01:35.140156", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-19T05:01:35.170395", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T05:01:35.177733", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T05:01:35.200764", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T05:02:36.076269", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T05:02:36.077974", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-19T05:02:36.102854", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T05:02:36.107898", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T05:02:36.132313", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T05:03:37.296806", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T05:03:37.298818", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-19T05:03:37.323195", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T05:03:37.326557", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T05:03:37.344273", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T05:04:37.872320", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T05:04:37.874158", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-19T05:04:37.902172", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T05:04:37.906091", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T05:04:37.926992", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T05:05:38.929218", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T05:05:38.932925", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-19T05:05:38.953293", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T05:05:38.955797", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T05:05:38.965742", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T05:06:40.000680", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T05:06:40.005327", "level": "ERROR", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "check_token_revocation", "line": 641, "message": "Failed to check token revocation status", "exception": {"type": "AttributeError", "message": "'_CachedRequest' object has no attribute 'begin'", "traceback": ["Traceback (most recent call last):\n", "  File \"/root/projects/school-attendance-management-software/app/services/auth_service.py\", line 628, in check_token_revocation\n    async with self.db.begin() as transaction:\n               ^^^^^^^^^^^^^\n", "AttributeError: '_CachedRequest' object has no attribute 'begin'\n"]}}
{"timestamp": "2025-01-19T05:06:40.018152", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
{"timestamp": "2025-01-19T05:06:40.022655", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 978, "message": "Attempting to verify token"}
{"timestamp": "2025-01-19T05:06:40.037833", "level": "DEBUG", "logger": "SchoolAttendanceLogger", "module": "auth_service", "function": "validate_token", "line": 998, "message": "Token validated successfully"}
